import sys
import os
import json
import time
import pytest
import asyncio
import threading
from pathlib import Path
from unittest.mock import MagicMock, patch

# Add project root to sys.path
project_root = Path(__file__).parent.parent.resolve()
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))

from services.provider_manager import ProviderManager
from services.failover_llm import FailoverChatModel
from providers.base_provider import BaseProviderAdapter
from langchain_core.messages import AIMessage, HumanMessage
from utils.metrics import metrics

# Helper to reset global metrics
def reset_global_metrics():
    metrics.success_counts.clear()
    metrics.failure_counts.clear()
    metrics.retry_counts.clear()
    metrics.latencies.clear()
    metrics.switch_count = 0
    metrics.active_provider = "None"
    metrics.all_failed_count = 0

@pytest.fixture(autouse=True)
def setup_env():
    # Setup mock env keys so all providers are loaded as configured
    with patch.dict(os.environ, {
        "GEMINI_API_KEY_1": "mock_gemini_key_1",
        "GEMINI_API_KEY_2": "mock_gemini_key_2",
        "GROQ_API_KEY_1": "mock_groq_key_1",
        "GROQ_API_KEY_2": "mock_groq_key_2"
    }):
        # Reset provider manager singleton instance
        ProviderManager._instance = None
        reset_global_metrics()
        yield

def test_config_loading_and_priority():
    """Verify that configuration loads providers and sorts them by priority correctly."""
    pm = ProviderManager()
    assert len(pm.providers) >= 4
    
    available = pm.get_available_providers()
    assert len(available) == 4
    # Ensure they are sorted by priority: 1, 2, 3, 4
    assert available[0]["id"] == "gemini_key_1"
    assert available[1]["id"] == "gemini_key_2"
    assert available[2]["id"] == "groq_key_1"
    assert available[3]["id"] == "groq_key_2"

@patch("providers.factory.ProviderFactory.create_provider")
def test_successful_request_primary(mock_create_provider):
    """Test successful response generated by the primary provider (Gemini Key 1)."""
    mock_adapter = MagicMock(spec=BaseProviderAdapter)
    mock_adapter.invoke.return_value = AIMessage(content="Hello from Gemini 1")
    mock_create_provider.return_value = mock_adapter

    pm = ProviderManager()
    llm = FailoverChatModel(provider_manager=pm)
    
    response = llm.invoke("Hi")
    
    assert response.content == "Hello from Gemini 1"
    assert metrics.success_counts["gemini_key_1"] == 1
    assert metrics.active_provider == "gemini_key_1"
    assert metrics.switch_count == 0

@patch("providers.factory.ProviderFactory.create_provider")
def test_failover_gemini1_to_gemini2(mock_create_provider):
    """Test failover to Gemini Key 2 when Gemini Key 1 has a permanent failure (e.g. invalid key)."""
    # Create adapters
    mock_adapter_1 = MagicMock(spec=BaseProviderAdapter)
    mock_adapter_1.invoke.side_effect = Exception("API_KEY_INVALID: Permission Denied")
    
    mock_adapter_2 = MagicMock(spec=BaseProviderAdapter)
    mock_adapter_2.invoke.return_value = AIMessage(content="Hello from Gemini 2")
    
    def side_effect(name, api_key, model, **kwargs):
        if api_key == "mock_gemini_key_1":
            return mock_adapter_1
        elif api_key == "mock_gemini_key_2":
            return mock_adapter_2
        return MagicMock(spec=BaseProviderAdapter)
        
    mock_create_provider.side_effect = side_effect

    pm = ProviderManager()
    llm = FailoverChatModel(provider_manager=pm)
    
    response = llm.invoke("Hi")
    
    assert response.content == "Hello from Gemini 2"
    # Verify switch and metrics
    assert metrics.failure_counts["gemini_key_1"] == 1
    assert metrics.success_counts["gemini_key_2"] == 1
    assert metrics.switch_count == 1
    assert metrics.active_provider == "gemini_key_2"

@patch("providers.factory.ProviderFactory.create_provider")
def test_failover_all_gemini_to_groq(mock_create_provider):
    """Test failover to Groq when both Gemini keys fail."""
    mock_gemini_1 = MagicMock(spec=BaseProviderAdapter)
    mock_gemini_1.invoke.side_effect = Exception("403: Forbidden billing error")
    
    mock_gemini_2 = MagicMock(spec=BaseProviderAdapter)
    mock_gemini_2.invoke.side_effect = Exception("API key expired")
    
    mock_groq_1 = MagicMock(spec=BaseProviderAdapter)
    mock_groq_1.invoke.return_value = AIMessage(content="Hello from Groq 1")
    
    def side_effect(name, api_key, model, **kwargs):
        if api_key == "mock_gemini_key_1":
            return mock_gemini_1
        elif api_key == "mock_gemini_key_2":
            return mock_gemini_2
        elif api_key == "mock_groq_key_1":
            return mock_groq_1
        return MagicMock(spec=BaseProviderAdapter)
        
    mock_create_provider.side_effect = side_effect

    pm = ProviderManager()
    llm = FailoverChatModel(provider_manager=pm)
    
    response = llm.invoke("Hi")
    
    assert response.content == "Hello from Groq 1"
    assert metrics.failure_counts["gemini_key_1"] == 1
    assert metrics.failure_counts["gemini_key_2"] == 1
    assert metrics.success_counts["groq_key_1"] == 1
    assert metrics.switch_count == 2
    assert metrics.active_provider == "groq_key_1"

@patch("providers.factory.ProviderFactory.create_provider")
@patch("time.sleep", return_value=None) # Skip actual sleep to run tests fast
def test_smart_retry_logic(mock_sleep, mock_create_provider):
    """Test smart retry logic on transient errors (like 429 rate limits)."""
    mock_gemini_1 = MagicMock(spec=BaseProviderAdapter)
    # Fail twice with 429, then succeed on 3rd attempt
    mock_gemini_1.invoke.side_effect = [
        Exception("Rate limit 429: Too Many Requests"),
        Exception("Rate limit 429: Too Many Requests"),
        AIMessage(content="Hello on attempt 3")
    ]
    mock_create_provider.return_value = mock_gemini_1

    pm = ProviderManager()
    llm = FailoverChatModel(provider_manager=pm)
    
    response = llm.invoke("Hi")
    
    assert response.content == "Hello on attempt 3"
    assert metrics.retry_counts["gemini_key_1"] == 2
    assert metrics.success_counts["gemini_key_1"] == 1
    # Check that sleep backoff was called twice
    assert mock_sleep.call_count == 2

@patch("providers.factory.ProviderFactory.create_provider")
def test_cooldown_and_recovery(mock_create_provider):
    """Test cooldown period and subsequent recovery attempt of a provider."""
    mock_gemini_1 = MagicMock(spec=BaseProviderAdapter)
    mock_gemini_1.invoke.side_effect = Exception("403 Unauthorized key") # Permanent error
    
    mock_gemini_2 = MagicMock(spec=BaseProviderAdapter)
    mock_gemini_2.invoke.return_value = AIMessage(content="Success on key 2")
    
    def side_effect(name, api_key, model, **kwargs):
        if api_key == "mock_gemini_key_1":
            return mock_gemini_1
        elif api_key == "mock_gemini_key_2":
            return mock_gemini_2
        return MagicMock(spec=BaseProviderAdapter)
        
    mock_create_provider.side_effect = side_effect

    pm = ProviderManager()
    llm = FailoverChatModel(provider_manager=pm)
    
    # 1. Call invokes failover to Key 2 because Key 1 failed
    res1 = llm.invoke("Hi")
    assert res1.content == "Success on key 2"
    assert "gemini_key_1" in pm.unhealthy_since
    
    # 2. Subsequent call should skip Key 1 immediately (still cooling down)
    mock_gemini_1.invoke.reset_mock()
    res2 = llm.invoke("Hi")
    assert res2.content == "Success on key 2"
    mock_gemini_1.invoke.assert_not_called()
    
    # 3. Simulate cooldown expiration (force unhealthy time to be 100s ago)
    pm.unhealthy_since["gemini_key_1"] = time.time() - 100
    mock_gemini_1.invoke.side_effect = None
    mock_gemini_1.invoke.return_value = AIMessage(content="Recovered key 1")
    
    res3 = llm.invoke("Hi")
    assert res3.content == "Recovered key 1"
    assert "gemini_key_1" not in pm.unhealthy_since

@patch("providers.factory.ProviderFactory.create_provider")
def test_concurrent_requests_thread_safety(mock_create_provider):
    """Verify thread safety under concurrent requests."""
    mock_adapter = MagicMock(spec=BaseProviderAdapter)
    mock_adapter.invoke.return_value = AIMessage(content="Thread response")
    mock_create_provider.return_value = mock_adapter

    pm = ProviderManager()
    llm = FailoverChatModel(provider_manager=pm)
    
    errors = []
    
    def worker():
        try:
            res = llm.invoke("Hi")
            assert res.content == "Thread response"
        except Exception as ex:
            errors.append(ex)
            
    threads = [threading.Thread(target=worker) for _ in range(10)]
    for t in threads:
        t.start()
    for t in threads:
        t.join()
        
    assert len(errors) == 0
    assert metrics.success_counts["gemini_key_1"] == 10
